## 正負情緒判斷

In [6]:
import pandas as pd
# import jieba

In [7]:
movies = pd.read_excel('https://raw.githubusercontent.com/ywchiu/pytextmining/master/data/yahoo_movie.xlsx')
print(movies.shape)
movies.head()

(1112, 5)


Unnamed: 0                                            content  stars title  \
0           0  不知道耶! 看完整個無感\r\n有種覺得就是女兒"給蕭"害死了老爸\r\n然後...既然可以...      3  古墓奇兵   
1           1  很好看的動作片，不會浪費錢跟時間。很久沒有這樣的探險片。可說是女版的印第安那瓊。女主角跟爸爸...      5  古墓奇兵   
2           2  說這個不好看的話，那我還真不知道，還有什麼片是您可以去看得了。電影好看，但話說羅拉有裝可以撿...      5  古墓奇兵   
3           3                                   父女重逢真的很讓人感動，五顆星。      5  古墓奇兵   
4           4  劇情雖然老套，但仍拍出新意，古墓能殺人的方式不就是機關和毒，要求亂七八糟的觀眾，你看喪尸片看多了。      4  古墓奇兵   

  status  
0   soso  
1   good  
2   good  
3   good  
4   good

In [8]:
movies = movies[movies['status'] != 'soso']
print(movies.shape)
movies.head()

(980, 5)


Unnamed: 0                                            content  stars title  \
1           1  很好看的動作片，不會浪費錢跟時間。很久沒有這樣的探險片。可說是女版的印第安那瓊。女主角跟爸爸...      5  古墓奇兵   
2           2  說這個不好看的話，那我還真不知道，還有什麼片是您可以去看得了。電影好看，但話說羅拉有裝可以撿...      5  古墓奇兵   
3           3                                   父女重逢真的很讓人感動，五顆星。      5  古墓奇兵   
4           4  劇情雖然老套，但仍拍出新意，古墓能殺人的方式不就是機關和毒，要求亂七八糟的觀眾，你看喪尸片看多了。      4  古墓奇兵   
5           5  每個演員都長得像路人，劇情解謎上都沒有作一些鋪陳，以致於每個謎題只有主角轉一轉就都破解了，覺...      2  古墓奇兵   

  status  
1   good  
2   good  
3   good  
4   good  
5    bad

In [4]:
import torch
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

print(torch.__version__)
print(device)

1.3.0
cuda


In [5]:
from transformers import BertTokenizer, BertModel, BertForMaskedLM

To use data.metrics please install scikit-learn. See https://scikit-learn.org/stable/index.html


In [6]:
# Load pre-trained model tokenizer (vocabulary)
tokenizer = BertTokenizer.from_pretrained('bert-base-chinese')

100%|██████████| 109540/109540 [00:00<00:00, 256568.89B/s]


In [7]:
# Load pre-trained model (weights)
model = BertModel.from_pretrained('bert-base-chinese')

100%|██████████| 411577189/411577189 [03:01<00:00, 2271338.07B/s]


In [8]:
# Tokenize input
text = "很好看的動作片，不會浪費錢跟時間。很久沒有這樣的探險片。可說是女版的印第安那瓊。"
tokenized_text = tokenizer.tokenize(text)
print(type(tokenized_text))
tokenized_text

<class 'list'>


['很',
 '好',
 '看',
 '的',
 '動',
 '作',
 '片',
 '，',
 '不',
 '會',
 '浪',
 '費',
 '錢',
 '跟',
 '時',
 '間',
 '。',
 '很',
 '久',
 '沒',
 '有',
 '這',
 '樣',
 '的',
 '探',
 '險',
 '片',
 '。',
 '可',
 '說',
 '是',
 '女',
 '版',
 '的',
 '印',
 '第',
 '安',
 '那',
 '瓊',
 '。']

In [9]:
# Convert token to vocabulary indices
indexed_tokens = tokenizer.convert_tokens_to_ids(tokenized_text)
print(type(indexed_tokens))
indexed_tokens

<class 'list'>


[2523,
 1962,
 4692,
 4638,
 1240,
 868,
 4275,
 8024,
 679,
 3298,
 3857,
 6527,
 7092,
 6656,
 3229,
 7279,
 511,
 2523,
 719,
 3760,
 3300,
 6857,
 3564,
 4638,
 2968,
 7402,
 4275,
 511,
 1377,
 6303,
 3221,
 1957,
 4276,
 4638,
 1313,
 5018,
 2128,
 6929,
 4475,
 511]

In [10]:
# Convert inputs to PyTorch tensors
tokens_tensor = torch.tensor([indexed_tokens])
tokens_tensor

tensor([[2523, 1962, 4692, 4638, 1240,  868, 4275, 8024,  679, 3298, 3857, 6527,
         7092, 6656, 3229, 7279,  511, 2523,  719, 3760, 3300, 6857, 3564, 4638,
         2968, 7402, 4275,  511, 1377, 6303, 3221, 1957, 4276, 4638, 1313, 5018,
         2128, 6929, 4475,  511]])

In [11]:
len(text)

40

In [12]:
segments_ids = [0,0]
for i in range(2, len(text)):
    segments_ids.append(0)

# Convert inputs to PyTorch tensors
segments_tensors = torch.tensor([segments_ids])
segments_tensors

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [13]:
# input_ids = torch.tensor([tokenizer.encode(text, add_special_tokens=True)])  
# # Add special tokens takes care of adding [CLS], [SEP], <s>... tokens in the right way for each model.

# input_ids

In [14]:
# Load pre-trained model (weights)
model = BertModel.from_pretrained('bert-base-chinese')

# Set the model in evaluation mode to deactivate the DropOut modules
# This is IMPORTANT to have reproducible results during evaluation!
model.eval()

# If you have a GPU, put everything on cuda
tokens_tensor = tokens_tensor.to('cuda')
segments_tensors = segments_tensors.to('cuda')
model.to('cuda')
tokens_tensor

tensor([[2523, 1962, 4692, 4638, 1240,  868, 4275, 8024,  679, 3298, 3857, 6527,
         7092, 6656, 3229, 7279,  511, 2523,  719, 3760, 3300, 6857, 3564, 4638,
         2968, 7402, 4275,  511, 1377, 6303, 3221, 1957, 4276, 4638, 1313, 5018,
         2128, 6929, 4475,  511]], device='cuda:0')

In [15]:
# Predict hidden states features for each layer
with torch.no_grad():
    # See the models docstrings for the detail of the inputs
    outputs = model(tokens_tensor, token_type_ids=segments_tensors)
    # Transformers models always output tuples.
    # See the models docstrings for the detail of all the outputs
    # In our case, the first element is the hidden state of the last layer of the Bert model
    encoded_layers = outputs[0]
# We have encoded our input sequence in a FloatTensor of shape (batch size, sequence length, model hidden dimension)
assert tuple(encoded_layers.shape) == (1, len(indexed_tokens), model.config.hidden_size)

In [ ]:
jieba.load_userdict('userdict.txt')
corpus = []
scores = []
for movie in movies.iterrows():
    corpus.append(' '.join(jieba.cut(movie[1].content)))
    scores.append(movie[1].status)


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)
X

In [ ]:
from sklearn.model_selection import train_test_split
train_X, test_X, train_Y, test_Y = train_test_split(X, scores, test_size = 0.3, random_state = 42)

In [ ]:
train_X.shape, test_X.shape, len(train_Y), len(test_Y)

In [ ]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB(alpha = 0.01)
clf.fit(train_X, train_Y)

In [ ]:
predicted = clf.predict(test_X)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(test_Y, predicted)

In [ ]:
from sklearn.metrics import confusion_matrix
print(clf.classes_)
confusion_matrix(test_Y, predicted)

In [ ]:
import operator
coef_features_c1_c2 = []

for index, features in enumerate(zip(vectorizer.get_feature_names(), \
                        clf.feature_count_[0], clf.feature_count_[1])):
    feat,c1,c2 = features
    coef_features_c1_c2.append(tuple([c2/(c1 + 1), feat, c1, c2]))

for i in sorted(coef_features_c1_c2, key = operator.itemgetter(0), reverse=True)[0:20]:
    print(i)


In [ ]:
import operator
coef_features_c1_c2 = []

for index, features in enumerate(zip(vectorizer.get_feature_names(), \
                        clf.feature_count_[0], clf.feature_count_[1])):
    feat,c1,c2 = features
    coef_features_c1_c2.append(tuple([c1/(c2 + 1), feat, c1, c2]))

for i in sorted(coef_features_c1_c2, key = operator.itemgetter(0), reverse=True)[0:20]:
    print(i)


In [ ]:
new_comment = '非常精彩值得一看 劇情豐富 出乎意料'
new_vec = vectorizer.transform([' '.join(jieba.cut(new_comment))])

In [ ]:
clf.predict(new_vec)